version: '3.3'

services:
  db_dolt:
    restart: always
    build:
      context: .
      dockerfile: ./services/db_dolt/dockerfile
    ports:
      - "3306:3306"
    volumes:
      - db_dolt:/db_dolt

volumes:
  db_dolt:
